### PR TITLE
Fixed the gemspec to properly detect the use of jruby, with the help …

### PR DESCRIPTION
**Pull request by ninkibah**
I changed the detection of jruby in the gemspec to use Gem::ruby_engine instead of Gem::Platform::RUBY.

### CODE REVIEW

**Comment by toadkicker** [comment]
Thanks for the PR! I actually took jruby out of the .travis.yml. We should add it back to test this properly. Do you mind adding that to the commits? Thanks for the PR!

**Comment by toadkicker** [comment]
I think it needs sudo: false to support their new container setup per http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by ninkibah** [comment]
@toadkicker I suspect this is breaking because it's trying to load sqllite3 which is probably not compatible with jruby without turning on c-extensions. As this is only a one word change, and it's working in my jruby app, I'm going to remove travis support for jruby.

Do you need a DB for the tests?

**Comment by toadkicker** [comment]
There is no reason to have sqlite installed there...lets see if there is a way to prevent Travis from doing that.

**Comment by ninkibah** [comment]
Todd, I've removed sqllite3 from the gemspec, and I'm trying to run the tests locally under jruby. I'll let you know if that works.

**Comment by ninkibah** [comment]
@toadkicker I've fixed the gemspec file to avoid loading non-jruby gems under jruby. I've also put back the jruby environment for travis. I created an rvm gemset specially for railsstrap and bundle install went cleanly, and the specs all ran cleanly. I think we should be good to go.

**Comment by toadkicker** [comment]
Thanks for everything!

**Comment by ninkibah** [comment]
@toadkicker You're welcome! Your comment about sqllite not needing to be there, was just the spur I needed to actually get the gem specs to work locally. I look forward to having you add the bootstrap helper methods for alerts, navbars, etc...

**Pull request merged**
